[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_lending_example = "HKViZ7i7fEpfqcpCpDWAfmZpuVZ6WSRXST85nf1w227q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn jest"
lint = "cargo fmt && cargo clippy"
build = "anchor build && cp ./target/idl/*.json ./sdk/src/idl/ && cp ./target/types/*.ts ./sdk/src/types/"